myv.max_size(): 1
Catching exception myv: vector

myv.capacity(): 0
myv.reserve(0);
myv.capacity(): 0
myv.capacity(): 1

myv.reserve(18446744073709551615);
Catching exception myv: allocator<T>::allocate(size_t n) 'n' exceeds maximum supported size
myv.capacity(): 8
myv.capacity(): 16
# launching clear twice
myv.capacity(): 16
                  myv < myv2: 1

                  myv > myv2: 0

                 myv == myv2: 0

                 myv != myv2: 0

                 myv <= myv2: 1

                 myv >= myv2: 0
